# Generated by Django 3.2.8 on 2021-11-05 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grammars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenNguPhap', models.CharField(max_length=255)),
                ('CachNhanBiet', models.CharField(max_length=255)),
                ('NguPhap', models.CharField(max_length=255)),
                ('CachDung', models.CharField(max_length=255)),
                ('Exams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exams')),
            ],
        ),
    ]
