# Generated by Django 3.2.8 on 2021-12-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammars',
            name='CachDung',
        ),
        migrations.RemoveField(
            model_name='grammars',
            name='CachNhanBiet',
        ),
        migrations.RemoveField(
            model_name='grammars',
            name='NguPhap',
        ),
        migrations.AddField(
            model_name='grammars',
            name='NoiDung',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
