# Generated by Django 3.2.8 on 2021-12-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammars', '0002_auto_20211219_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammars',
            name='NoiDung',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
