# Generated by Django 3.2.8 on 2021-12-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammars', '0003_alter_grammars_noidung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammars',
            name='NoiDung',
            field=models.CharField(blank=True, max_length=99999, null=True),
        ),
    ]
