# Generated by Django 3.2.8 on 2021-12-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammars', '0004_alter_grammars_noidung'),
    ]

    operations = [
        migrations.CreateModel(
            name='NguPhap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenNguPhap', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='grammars',
            name='Exams',
        ),
    ]
