# Generated by Django 3.2.8 on 2021-12-27 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grammars', '0005_auto_20211227_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammars',
            name='TenNguPhap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grammars.nguphap'),
        ),
    ]
