# Generated by Django 3.2.8 on 2021-12-27 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grammars', '0006_alter_grammars_tennguphap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammars',
            name='TenNguPhap',
        ),
    ]
