# Generated by Django 3.2.8 on 2021-11-05 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenExam', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CauHoi', models.CharField(max_length=255)),
                ('Diem', models.IntegerField(default=0)),
                ('Exams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exams')),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DapAn', models.CharField(max_length=255)),
                ('DapAnDung', models.CharField(max_length=255)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.questions')),
            ],
        ),
    ]
