# Generated by Django 3.2.8 on 2021-12-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20211216_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='CauHoi',
            field=models.CharField(max_length=9999),
        ),
    ]
