# Generated by Django 3.2.8 on 2021-12-27 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_questions_cauhoi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamsKiemtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenExam', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Questionskiemtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CauHoi', models.CharField(max_length=9999)),
                ('Diem', models.IntegerField(default=0)),
                ('DapAnDung', models.CharField(blank=True, max_length=255, null=True)),
                ('DapAnA', models.CharField(blank=True, max_length=255, null=True)),
                ('DapAnB', models.CharField(blank=True, max_length=255, null=True)),
                ('DapAnC', models.CharField(blank=True, max_length=255, null=True)),
                ('DapAnD', models.CharField(blank=True, max_length=255, null=True)),
                ('Exams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exams')),
            ],
        ),
    ]
