# Generated by Django 3.2.8 on 2021-12-27 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_examskiemtra_questionskiemtra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamsKiemtra',
            new_name='examsktra',
        ),
        migrations.RenameModel(
            old_name='Questionskiemtra',
            new_name='questionktra',
        ),
    ]
