# Generated by Django 3.2.8 on 2021-12-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0002_sounds_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sounds',
            name='Link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
