# Generated by Django 3.2.8 on 2021-12-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0003_alter_sounds_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sounds',
            name='Link',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
