# Generated by Django 3.2.8 on 2021-12-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0005_alter_sounds_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sounds',
        ),
    ]
