# Generated by Django 3.2.8 on 2021-11-05 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('sounds', '0001_initial'),
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NewWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenTA', models.CharField(blank=True, max_length=255, null=True)),
                ('NghiaTV', models.CharField(blank=True, max_length=255, null=True)),
                ('VdTA', models.CharField(blank=True, max_length=255, null=True)),
                ('PhatAm', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CachDoc', models.CharField(blank=True, max_length=255, null=True)),
                ('Exams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exams')),
                ('Sound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.sounds')),
                ('Topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoiDungTA', models.CharField(blank=True, max_length=255, null=True)),
                ('NoiDungTV', models.CharField(blank=True, max_length=255, null=True)),
                ('Exams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exams')),
                ('Topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.topic')),
            ],
        ),
        migrations.CreateModel(
            name='OldWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NewWords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.newwords')),
            ],
        ),
    ]
