# Generated by Django 3.2.8 on 2021-11-05 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partofspeech', '0001_initial'),
        ('sounds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0001_initial'),
        ('topic', '0002_listening_newwords_oldwords_reading_speaking'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldwords',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newwords',
            name='PoS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partofspeech.partofspeechs'),
        ),
        migrations.AddField(
            model_name='newwords',
            name='Sound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.sounds'),
        ),
        migrations.AddField(
            model_name='newwords',
            name='Topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.topic'),
        ),
        migrations.AddField(
            model_name='listening',
            name='Exams',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exams'),
        ),
        migrations.AddField(
            model_name='listening',
            name='Sound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.sounds'),
        ),
        migrations.AddField(
            model_name='listening',
            name='Topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.topic'),
        ),
    ]
