# Generated by Django 3.2.8 on 2021-12-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_auto_20211105_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='newwords',
            name='VdTV',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
