# Generated by Django 3.2.8 on 2021-12-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_newwords_vdtv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newwords',
            name='VdTV',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
