# Generated by Django 3.2.8 on 2021-12-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0008_remove_newwords_vdtv'),
    ]

    operations = [
        migrations.AddField(
            model_name='listening',
            name='DapAn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newwords',
            name='VdTV',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='listening',
            name='Exams',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
