# Generated by Django 3.2.8 on 2021-12-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0009_auto_20211207_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listening',
            old_name='Exams',
            new_name='CauHoi',
        ),
    ]
