# Generated by Django 3.2.8 on 2021-12-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0013_alter_newwords_sound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newwords',
            name='Sound',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
