# Generated by Django 3.2.8 on 2021-12-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0018_alter_newwords_sound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newwords',
            name='Sound',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
