# Generated by Django 3.2.8 on 2021-12-12 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0022_auto_20211212_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listening',
            name='Sound',
        ),
        migrations.RemoveField(
            model_name='newwords',
            name='Sound',
        ),
    ]
