# Generated by Django 3.2.8 on 2021-12-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0024_auto_20211212_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='NoiDungTA',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='NoiDungTV',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
