# Generated by Django 3.2.8 on 2021-12-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0025_auto_20211216_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='NoiDungTA',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='NoiDungTV',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
    ]
